numpy : 수치해석용 파이썬 패키지. 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용

1. numpy 배열

In [3]:
import numpy as np

1차원 배열 만들기

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9]) 
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy의 array 함수에 리스트를 넣으면 ndarray 클래스 객체 즉, 배열로 변환해 준다.

In [4]:
type(ar)

numpy.ndarray

벡터화 연산

In [6]:
data = [0,1,2,3,4,5,6,7,8,9]

In [7]:
# for 반복문을 이용한 경우
answer = []
for di in data : 
    answer.append(2*di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
x = np.array(data) # 벡터화 연산을 사용하면 훨씬 빠름
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [1]:
l = [0,1,2,3,4,5,6,7,8,9]
print(2*l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## 2차원 배열 만들기 
- list of list를 이용하면 2차원 배열이 생성된다.

In [11]:
c = np.array([[0,1,2,],[3,4,5]]) # 2x3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
#행의 갯수
len(c)

2

In [13]:
# 열의 갯수
len(c[0])

3

In [14]:
# 연습 문제1
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기

크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시

In [4]:
d = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
             [[11,12,13,14],
             [15,16,17,18],
             [19,20,21,22]]]) # 2 x 3 x 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [18]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

배열의 차원과 크기 알아내기 : 배열의 ndim 속성과 shape 속성을 이용

ndim 속성은 배열의 차원, shape 속성은 배열의 크기를 반환

In [19]:
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [22]:
c = np.array([[0,1,2],[3,4,5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


배열의 인덱싱

-리스트의 인덱싱과 같다.

In [5]:
a = np.array([0,1,2,3,4])
a[2]

2

In [6]:
a[-1]

4

In [27]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
a[0,0] # 첫번째 행의 첫번째 열

0

In [29]:
a[0,1] #첫번째 행의 두번째 열

1

In [30]:
a[-1,-1] # 마지막 행의 마지막 열

5

배열 슬라이싱

In [50]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [51]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [52]:
a[:, 1] # 두 번째 열 전체

array([1, 5])

In [53]:
a[1,1:] # 두 번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [56]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

- 연습 문제2

In [8]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [10]:
m[1,2]

7

In [11]:
m[2,4]

14

In [13]:
m[1,1:3]

array([6, 7])

In [15]:
m[1:,2]

array([ 7, 12])

In [16]:
m[0:2,3:]

array([[3, 4],
       [8, 9]])

array indexing(배열 인덱싱) or fancy indexing(팬시 인덱싱)

1) Boolean(불리언) 배열 방식

크기가 ndarray 객체의 크기와 같아야 한다.

In [36]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [39]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [40]:
a % 2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [41]:
a[a % 2 ==0]

array([0, 2, 4, 6, 8])

In [42]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8]) # 배열의 크기와 달라도 상관없음
a[idx]

array([11, 33, 55, 77, 99])

In [17]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [44]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [46]:
a[[2, 0, 1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

- 연습문제3

In [18]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [21]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [22]:
x[(x%3==0)&(x%4==1)]

array([9])