In [2]:
import numpy as np

- ndarray클래스는 원소가 모두 같은 자료형이어야 한다.

In [3]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [4]:
x=np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [6]:
x=np.array([1,2,3.0])
x.dtype

dtype('float64')

- b : 불리언
- i : 정수
- u : 부호 없는 정수
- f : 부동소수점
- c : 복소 부동소수점
- O : 객체
- s : 바이트 문자열
- U : 유니코드 문자열

In [7]:
x=np.array([1,2,3],dtype='f')
x.dtype

dtype('float32')

In [8]:
x[0]+x[1]

3.0

In [10]:
x=np.array([1,2,3],dtype='U')
x.dtype

dtype('<U1')

In [11]:
x[0]+x[1]

'12'

### Inf와 NaN
- 넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.

In [12]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

C:\Users\82109\AppData\Local\Temp/ipykernel_20564/1727448928.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
C:\Users\82109\AppData\Local\Temp/ipykernel_20564/1727448928.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [13]:
np.log(0)

C:\Users\82109\AppData\Local\Temp/ipykernel_20564/2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [14]:
np.exp(-np.inf)

0.0

### 배열 생성

- 크기가 정해져 있고 모든 값이 0인 배열을 생성

In [15]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [16]:
b=np.zeros((2,3)) # 튜플 입력
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
c = np.zeros((5,2),dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

- 문자열 배열도 가능하지만 모든 원소의 문자열 크기가 같아야 한다. 더 큰 크기의 문자열을 할당하면 잘릴 수 있다.

In [18]:
d = np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [19]:
d[0] ='abc'
d[1] = 'abcd'
d[2] = "ABCD"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [20]:
e = np.ones((2,3,4), dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

- 만약 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다면 ones_like, zeros_like 명령을 사용

In [21]:
f = np.ones_like(b, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [22]:
g = np.empty((4,3)) # 배열을 생성만 하고 특정한 값으로 초기화 하지 않는 명령
g

array([[1.04001409e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 7.56587583e-307, 3.85652214e-057],
       [1.26757138e-071, 9.27725207e-072, 3.14137902e+179],
       [1.77393908e+160, 1.20210282e-075, 2.10648167e-076]])

In [23]:
np.arange(10) # 특정한 규칙에 따라 증가하는 수열을 만듬

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(3,21,2) # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

- linspace나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할

In [25]:
np.linspace(0,100,5) # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [26]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

### 전치 연산

In [27]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 배열의 크기 변형

- 만들어진 배열의 내부 데이터는 보존한 채 형태만 바꿀 때

In [29]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 사용하는 원소의 갯수가 정해져 있기 때문에 reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수 있다. -1을 넣으면 해당 숫자는 다른 값에서 계산되어 사용된다.

In [31]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [34]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

- 다차원 배열을 무조건 1차원으로 만들기 위해서는 flatten이나 ravel 메서드를 사용한다.

In [35]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 길이가 5인 1차원 배열과 행, 열의 갯수가 (5,1)인 2차원 배열 또는 행, 열의 갯수가 (1,5)인 2차원 배열은 데이터가 같아도 엄연히 다른 객체라는 점이다.

In [38]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [39]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [40]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [41]:
x[:,np.newaxis] # 같은 배열에 대해 차원만 1차원 증가

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 배열 연결
- 행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하여 더 큰 배열을 만들 때 다음과 같은 명령어를 사용한다.

In [42]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

- hstack : 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만든다. 연결한 배열은 하나의 리스트에 담아야 한다.

In [45]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [46]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- vstack : 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만든다. 마찬가지로 연결한 배열은 하나의 리스트에 담아야 한다.

In [48]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- dstack : 제3의 축 즉, 행이나 열이 아닌 깊이(depth)방향으로 배열을 합친다. 가장 안쪽의 원소의 차원이 증가한다. 즉 가장 내부의 숫자 원소가 배열이 된다.

In [51]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [52]:
(np.dstack([c1,c2])).shape

(3, 4, 2)

- stack : dstack의 기능을 확장한 것으로 dstack처럼 마지막 차원으로 연결하는 것이 아니라 사용자가 지정한 차원(축으로) 배열을 연결한다. axis 인수(디폴트 0)를 사용하여 연결후의 회전 방향을 정한다. 디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성된다. 즉, 배열 두 개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 한다.

In [53]:
c=np.stack([c1,c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
c.shape

(2, 3, 4)

In [55]:
c = np.stack([c1,c2],axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [56]:
c.shape # 2개의 (3x4) -> 1개의 (3x2x4)

(3, 2, 4)

- r_ : hstack과 비슷하게 배열을 좌우로 연결한다. 다만 메서드임에도 불구하고 소괄호를 사용하지 않고 인덱싱과 같이 대괄호를 사용한다. 이런 특수 메서드를 인덱서(indexer)라고 한다.

In [59]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

- c_ : 배열의 차원을 증가시킨 후 좌우로 연결한다.

In [60]:
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

- tile : 동일한 배열을 반복하여 연결

In [61]:
a=np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [62]:
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### 2차원 그리드 포인트 생성
- 변수가 2개인 2차원 함수의 그래프를 그리거나 표를 작성하려면 2차원 영역에 대한 (x,y) 좌표값 쌍 즉, 그리드 포인트(grid point)를 생성하여 각 좌표에 대한 함수 값을 계산해야 한다.
- 이러한 그리드 포인트를 만드는 과정을 도와주는 것이 meshgrid 명령이다. meshgrid 명령은 사각형 영역을 구성하는 가로축의 점들과 세로축의 점을 나타내는 두 벡터를 인수로 받아서 이 사각형 영역을 이루는 조합을 출력한다. 결과는 그리드 포인트의 x값만을 표시하는 행렬과 y 값만을 표시하는 행렬 두 개로 분리하여 출력한다.

In [94]:
x=np.arange(3)
x

array([0, 1, 2])

In [95]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [96]:
X,Y=np.meshgrid(x,y)

In [97]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [98]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [99]:
[list(zip(x,y)) for x,y in zip(X,Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]