In [6]:
import numpy as np

### 벡터화 연산

In [7]:
x=np.arange(1,10001)
y=np.arange(10001,20001)

- 셀 코드의 실행시간을 측정하는 아이파이썬(IPython) 매직(magic)명령

In [8]:
%%time  
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i]+y[i] # 반복문을 사용했을 때

Wall time: 4.99 ms


In [9]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [10]:
%%time
z=x+y

Wall time: 364 µs


In [11]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [12]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [13]:
a == b

array([False,  True, False,  True])

In [14]:
a >= b

array([False,  True,  True,  True])

In [15]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [16]:
np.all(a==b) # 배열의 모든 원소가 다 같은지 알고 싶을 때

False

In [17]:
np.all(a==c)

True

In [18]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [19]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [20]:
10**a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [21]:
np.log(a+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
100*x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [24]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
100*x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

### 브로드캐스팅
- 서로 다른 크기를 가진 두 배열의 사칙 연산을 할 때 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법

In [26]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [27]:
y=np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [28]:
x+y

array([1, 2, 3, 4, 5])

In [29]:
x+1

array([1, 2, 3, 4, 5])

In [30]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [31]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [32]:
x+y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [33]:
y = np.arange(3)
y

array([0, 1, 2])

In [34]:
x+y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

### 차원 축소 연산

In [35]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [36]:
np.sum(x)

10

In [37]:
x.sum()

10

In [38]:
x = np.array([1,3,2])

In [39]:
x.min()

1

In [40]:
x.max()

3

In [41]:
x.argmin() #최솟값의 위치

0

In [42]:
x.argmax() #최댓값의 위치

1

In [43]:
x=np.array([1,2,3,1])

In [44]:
x.mean()

1.75

In [45]:
np.median(x)

1.5

In [46]:
np.all([True, True, False])

False

In [47]:
np.any([True, True, False])

True

In [48]:
a = np.zeros((100,100),dtype=int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [49]:
np.any(a != 0)

False

In [50]:
np.all(a == a)

True

In [51]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

In [52]:
((a<=b)&(b<=c)).all()

True

- 연산의 대상이 2차원 이상의 경우에는 어느 차원으로 계산을 할 지를 axis 인수를 사용하여 지시한다. axis=0인 경우는 열 연산, axis=1인 경우는 행 연산이다. 디폴트 값은 axis=0. axis 인수는 대부분의 차원 축소 명령에 적용할 수 있다.

In [53]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [54]:
x.sum()

6

In [55]:
x.sum(axis=0)

array([3, 3])

In [56]:
x.sum(axis=1)

array([2, 4])

#### 연습 문제 3.3.1

In [57]:
q1 = np.arange(30).reshape(5,6)
q1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [58]:
q1.max()

29

In [59]:
q1.sum(axis=0)

array([60, 65, 70, 75, 80, 85])

In [60]:
q1.max(axis=1)

array([ 5, 11, 17, 23, 29])

In [61]:
q1.mean(axis=0)

array([12., 13., 14., 15., 16., 17.])

In [62]:
q1.min(axis=0)

array([0, 1, 2, 3, 4, 5])

### 정렬
- sort 함수나 메서드를 사용하여 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열을 만들 수도 있다. 2차원 이상인 경우에는 행이나 열을 각각 따로따로 정렬하는데 axis 인수를 사용하여 행을 정렬할 것인지 열을 정렬할 것인지 결정한다. axis=0이면 각각의 행을 따로따로 정렬하고 axis=1이면 각각의 열을 따로따로 정리한다. 디폴트 값은 -1로 가장 안쪽의 차원이다.

In [63]:
a = np.array([[4,3,5,7],
             [1,12,11,9],
            [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [64]:
np.sort(a) # axis=-1 또는 axis=1과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [65]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [66]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [70]:
a = np.array([42,38,12,25])
j = np.argsort(a) # 자료를 정렬하는 것이 아니라 순서만 알고 싶을 때
j

array([2, 3, 1, 0], dtype=int64)

In [71]:
a = np.array([42,38,12,25])
j = np.argsort(-a) # 자료를 정렬하는 것이 아니라 순서만 알고 싶을 때
j

array([0, 1, 3, 2], dtype=int64)

In [68]:
a[j]

array([42, 38, 25, 12])

In [69]:
np.sort(a)

array([12, 25, 38, 42])