In [1]:
import numpy as np

### 시드 설정

In [2]:
np.random.seed(0) # 0과 같거나 큰 정수

- rand 함수는 0과 1 사이의 난수를 발생시키는 함수로 인수로 받은 숫자 횟수만큼 난수를 발생시킨다.

In [3]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [4]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [5]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [6]:
np.random.seed(0) # 시드 재설정

In [7]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [8]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [9]:
np.random.rand(10) # 같은 숫자 출력됨

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

### 데이터 순서 바꾸기
- shuffle 함수를 사용. shuffle 함수도 자체 변환(in-place)함수로 한 번 사용하면 변수의 값이 바뀌므로 주의해야 한다.

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.random.shuffle(x)
x

array([6, 3, 9, 2, 8, 7, 5, 4, 1, 0])

### 데이터 샘플링
- choice 함수 사용.
- a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
- size : 정수. 샘플 숫자
- replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능
- p : 배열. 각 데이터가 선택될 수 있는 확률

In [14]:
np.random.choice(5,5,replace=False) # shuffle 명령과 같다.

array([1, 4, 3, 0, 2])

In [16]:
np.random.choice(5,3,replace=False)

array([3, 0, 2])

In [17]:
np.random.choice(5,10) # 반복해서 10개 선택

array([4, 1, 1, 0, 1, 1, 1, 1, 0, 4])

In [18]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0]) # 선택 확률을 다르게 해서 10개 선택

array([3, 3, 2, 0, 3, 3, 3, 3, 2, 2])

### 난수 생성
- rand : 0부터 1사이의 균일 분포
- randn : 표준 정규 분포
- randint : 균일 분포의 정수 난수

In [19]:
np.random.rand(10)

array([0.14212014, 0.78331447, 0.41253884, 0.03417131, 0.62402999,
       0.66063573, 0.29849529, 0.44613451, 0.22212455, 0.07336417])

In [20]:
np.random.rand(3,5)

array([[0.46923853, 0.09617226, 0.90337017, 0.11949047, 0.52479938],
       [0.083623  , 0.91686133, 0.91044838, 0.29893011, 0.58438912],
       [0.56591203, 0.61393832, 0.95653566, 0.26097898, 0.23101542]])

In [21]:
np.random.randn(10)

array([ 0.6393049 ,  0.04752605,  3.11483365, -0.53246159,  0.34558368,
       -0.42551404, -2.23877138,  1.75539696, -0.26419336,  0.84629447])

In [22]:
np.random.randn(3,5)

array([[ 2.0867325 ,  0.52647831,  0.983809  , -1.92220001, -0.89482523],
       [ 0.33006282,  1.048591  ,  1.34989935,  1.24567511, -0.69119147],
       [ 1.28107338, -0.72706431, -0.79916869, -0.00354562,  0.51259464]])

- randint 함수 인수
- numpy.random.randint(low, high=None, size=None)
- high를 입력하지 않으면 0과 low 사이의 숫자를, high를 입력하면 low와 high는 사이의 숫자를 출력한다. size는 난수의 숫자

In [25]:
np.random.randint(10,size=10)

array([7, 8, 9, 5, 7, 0, 9, 3, 9, 1])

In [26]:
np.random.randint(10,20,size=10)

array([14, 14, 16, 18, 18, 19, 12, 17, 15, 15])

In [27]:
np.random.randint(10,20,size=(3,5))

array([[14, 15, 18, 15, 18],
       [11, 11, 18, 17, 10],
       [13, 14, 12, 10, 13]])

#### 연습 문제 3.5.1

In [33]:
q1 = np.random.randint(0,2,size=10)
q1

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1])

In [34]:
q2 = np.random.randint(0,2,size=100).mean()
q2

0.4

#### 연습 문제 3.5.2

In [35]:
np.random.randn(250)

array([-1.67860864e-01, -2.09724060e+00, -4.48630634e-01,  4.70559593e-01,
       -1.39857823e+00,  5.48882898e-01, -2.47515015e-01, -2.25127476e-01,
        3.79691880e-01, -1.15694754e-01, -1.46620101e-01,  1.76939854e+00,
       -3.21878358e-03, -6.66460132e-01, -7.71836011e-01, -2.64960679e-01,
        1.10728223e+00, -1.34873652e+00,  5.90902752e-01,  3.79550710e-02,
       -9.52724019e-01, -1.20102365e+00, -7.90439789e-02,  7.89893345e-01,
        2.18617751e+00, -9.26690996e-01,  4.01845265e-01, -7.95893042e-01,
        7.20232488e-01,  1.49161166e+00,  1.01177037e-01,  1.09823813e+00,
        1.15155406e-01,  1.32243076e+00,  9.83158730e-01,  1.25718996e+00,
        4.62572041e-01, -9.15033222e-01,  8.82388475e-01,  7.35969849e-01,
       -1.35136197e+00,  1.12422540e+00, -5.86403112e-01,  1.45999738e+00,
       -2.78077889e-01,  4.36612771e-01,  3.82216401e-02,  1.49007700e+00,
        2.59779071e+00, -3.62915614e-01, -9.16934497e-01,  9.54016382e-01,
       -3.51376813e-01,  

### 정수 데이터 카운팅
- 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석할 수 있다.
- unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력한다.
- return_counts 인수를 True로 설정하면 각 값을 가진 데이터 갯수도 출력한다.

In [36]:
np.unique([11,2,2,34,34])

array([ 2, 11, 34])

In [37]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts=True)

In [38]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [39]:
count

array([2, 2, 1], dtype=int64)

- unique 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않는다.
- 데이터가 특정 범위 안의 수인 경우에는 bincount함수에 minlength인수를 설정하는 것이 더 편리하다. bincount함수는 0부터 minlength -1까지의 숫자에 대해 각각 카운트를 한다. 데이터가 없을 경우에는 카운트 값이 0이 된다.

In [40]:
np.bincount([1,1,2,2,2,3],minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)