In [2]:
import pandas as pd

### 시리즈 클래스
- Series 클래스는 넘파이에서 제공하는 1차원 배열과 비슷하지만 각 데이터의 의미를 표시하는 인덱스(index)를 붙일 수 있다.데이터 자체는 값(value)라고 한다.
- 시리즈 = 값(value) + 인덱스(index)

#### 시리즈 생성
- 데이터를 리스트나 1차원 배열 형식으로 Series 클래스 생성자에 넣어주면 시리즈 클래스 객체를 만들 수 있다. 이 때 인덱스의 길이는 데이터의 길이와 같아야 한다.

In [3]:
s = pd.Series([9904312,3448737,2890451,2466052],
             index=['서울','부산','인천','대구']) # 인덱스 라벨 : 문자열 뿐만 아니라 날짜, 시간, 정수 등도 가능
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [4]:
pd.Series(range(10,14)) # 인덱스를 지정하지 않을 경우 0부터 시작.

0    10
1    11
2    12
3    13
dtype: int64

In [5]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [6]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [7]:
s.name = "인구"
s.index.name = "도시"
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

#### 시리즈 연산
- 시리즈도 벡터화 연산이 가능하지만 연산은 시리즈의 값에만 적용되며 인덱스 값은 변하지 않는다.

In [8]:
s/1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

#### 시리즈 인덱싱
- 시리즈 데이터를 인덱싱하면 값이 나온다.

In [9]:
s[1],s["부산"]

(3448737, 3448737)

In [10]:
s[3], s["대구"]

(2466052, 2466052)

In [11]:
s[[0,3,1]] # 배열 인덱싱을 할 경우 부분적인 값을 가지는 시리즈 자료형을 반환한다.

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [12]:
s[['서울','대구','부산']]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [13]:
s[(250e4<s)&(s<500e4)] # 인구가 250만 초과, 500만 미만인 경우

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [14]:
s[1:3] # 네번째(3) 미포함

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [15]:
s['부산':'대구'] # 대구도 포함

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [16]:
s0 = pd.Series(range(3),index=['a','b','c'])
s0

a    0
b    1
c    2
dtype: int64

In [17]:
s0.a

0

In [18]:
s0.b

1

#### 시리즈와 딕셔너리 자료형

In [19]:
"서울" in s

True

In [20]:
"대전" in s

False

- items 메서드를 사용하면 for 루프를 통해 각 원소의 키(key)와 값(value)을 접근할 수도 있다.

In [21]:
for k, v in s.items():
    print('%s = %d' % (k,v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


- 딕셔너리 객체에서 시리즈를 만들 수도 있다. 

In [22]:
s2 = pd.Series({'서울':9631482, '부산':3393191,'인천':2632035 ,'대전':1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

- 딕셔너리의 원소는 순서를 가지지 않으므로 시리즈의 데이터도 순서가 보장되지 않는다. 순서를 정하고 싶으면 인덱스를 리스트로 지정해야 한다.

In [23]:
s2 = pd.Series({'서울':9631482, '부산':3393191,'인천':2632035 ,'대전':1490158},
              index = ['부산','서울','인천','대전'])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

#### 인덱스 기반 연산

In [24]:
ds = s- s2
ds  # 인덱스가 같은 데이터에 대해서만 차이를 구한다.

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

- NaN 값이 float 자료형에서만 가능하므로 다른 계산 결과도 모두 float 자료형이 된다.

In [25]:
s.values - s2.values

array([ 6511121, -6182745,   258416,   975894], dtype=int64)

In [26]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [27]:
s2.values

array([3393191, 9631482, 2632035, 1490158], dtype=int64)

In [28]:
ds.notnull() # NaN이 아닌 값을 구할 때 

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [29]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [30]:
rs = (s-s2) / s2*100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

#### 데이터의 갱신, 추가, 삭제
- 인덱싱 이용하면 데이터를 갱신하거나 추가할 수 있다.

In [31]:
rs['부산'] = 1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [32]:
rs['대구'] = '1.41'
rs

부산        1.63
서울     2.83269
인천    9.818107
대구        1.41
dtype: object

In [33]:
del rs['서울'] # 데이터 삭제
rs

부산        1.63
인천    9.818107
대구        1.41
dtype: object

### 데이터프레임 클래스

#### 데이터프레임 생성

In [35]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
} # 일차원 배열 준비 -> 각각의 열에 대한 라벨을 키로 가지는 딕셔너리를 만든다
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"] # 열방향 인덱스
index = ["서울", "부산", "인천", "대구"] # 행방향 인덱스
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [39]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 24561016, 2473990, 0.0141]], dtype=object)

In [40]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [41]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [42]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성   지역     2015     2010      2005     2000  2010-2015 증가율
도시                                                         
서울  수도권  9904312  9631482   9762546  9853972         0.0283
부산  경상권  3448737  3393191   3512547  3655437         0.0163
인천  수도권  2890451  2632035   2517680  2466338         0.0982
대구  경상권  2466052  2431774  24561016  2473990         0.0141

In [43]:
df.T

도시                  서울       부산       인천        대구
특성                                                
지역                 수도권      경상권      수도권       경상권
2015           9904312  3448737  2890451   2466052
2010           9631482  3393191  2632035   2431774
2005           9762546  3512547  2517680  24561016
2000           9853972  3655437  2466338   2473990
2010-2015 증가율   0.0283   0.0163   0.0982    0.0141

#### 열 데이터의 갱신, 추가, 삭제

In [44]:
# '2010-2015 증가율'이라는 이름의 열 추가
df['2010-2015 증가율'] = df['2010-2015 증가율']*100
df

특성   지역     2015     2010      2005     2000  2010-2015 증가율
도시                                                         
서울  수도권  9904312  9631482   9762546  9853972           2.83
부산  경상권  3448737  3393191   3512547  3655437           1.63
인천  수도권  2890451  2632035   2517680  2466338           9.82
대구  경상권  2466052  2431774  24561016  2473990           1.41

In [45]:
# '2005-2010 증가율'이라는 이름의 열 추가
df['2005-2010 증가율'] = ((df['2010']-df['2005']) / df['2005']*100).round(2)
df

특성   지역     2015     2010      2005     2000  2010-2015 증가율  2005-2010 증가율
도시                                                                        
서울  수도권  9904312  9631482   9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191   3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035   2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  24561016  2473990           1.41         -90.10

In [46]:
# '2010-2015 증가율'이라는 이름의 열 삭제
del df['2010-2015 증가율']
df

특성   지역     2015     2010      2005     2000  2005-2010 증가율
도시                                                         
서울  수도권  9904312  9631482   9762546  9853972          -1.34
부산  경상권  3448737  3393191   3512547  3655437          -3.40
인천  수도권  2890451  2632035   2517680  2466338           4.54
대구  경상권  2466052  2431774  24561016  2473990         -90.10

#### 열 인덱싱
- 인덱스로 라벨값을 하나만 넣으면 시리즈 객체가 반환되고 라벨의 배열 또는 리스트를 넣으면 시리즈 객체가 반환되고 라벨의 배열 또는 리스트를 넣으면 부분적인 데이터프레임이 반환된다.

In [47]:
df['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [48]:
df[['2010','2015']]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

- 하나의 열만 빼내면서 데이터프레임 자료형을 유지하고 싶다면 원소가 하나인 리스트를 써서 인덱싱 한다.

In [49]:
df[['2010']] 

특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [50]:
type(df[['2010']])

pandas.core.frame.DataFrame

In [51]:
df['2010'] # 열을 반환하면서 시리즈 자료형으로 변환

도시
서울    9631482
부산    3393191
인천    2632035
대구    2431774
Name: 2010, dtype: int64

In [52]:
type(df['2010'])

pandas.core.series.Series

In [53]:
df[0]

KeyError: 0

In [55]:
import numpy as np

- 정수형 열 인덱스를 가지는 경우에는 인덱스 값으로 정수를 사용할 수 있다.

In [56]:
df2 = pd.DataFrame(np.arange(12).reshape(3,4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [58]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int32

In [59]:
df2[[1,2]]

1   2
0  1   2
1  5   6
2  9  10

#### 행 인덱싱
- 행 단위로 인덱싱을 하고자 하면 항상 슬라이싱(slicing)을 해야 한다.

In [60]:
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [61]:
df[1:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           -3.4

In [62]:
df[1:3]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [63]:
df['서울':'부산']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

#### 개별 데이터 인덱싱
- 데이터프레임에서 열 라벨로 시리즈를 인덱싱하면 시리즈
- 이 시리즈를 다시 행 라벨로 인덱싱하면 개별 데이터

In [64]:
df['2015']['서울']

9904312

#### 연습문제 4.1.3

In [66]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [73]:
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [77]:
type(df['수학'])

pandas.core.series.Series

In [76]:
df[['국어','영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [78]:
type(df[['국어','영어']])

pandas.core.frame.DataFrame

In [81]:
df['평균'] = (df['국어']+df['영어']+df['수학'])/3
df

국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  40  70  46.666667

In [84]:
df['영어']['방자']=80
df

C:\Users\82109\AppData\Local\Temp/ipykernel_14592/2712220688.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['영어']['방자']=80


국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  80  70  46.666667

In [85]:
df['평균'] = (df['국어']+df['영어']+df['수학'])/3
df

국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  80  70  60.000000

In [87]:
df[:1]

국어  영어  수학         평균
춘향  80  90  90  86.666667

In [99]:
df.loc['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64

In [98]:
type(df.loc['향단'])

pandas.core.series.Series